# Generated by Django 4.1.7 on 2023-02-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Proyecto/imagen')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
